import { OAuthProvider, type AuthRequest, type OAuthHelpers } from "@cloudflare/workers-oauth-provider";

const CHECKPOINT_KEY = "community-manager:last-checked-at";
const REASONS = new Set(["like", "follow", "reply", "mention", "quote", "repost"]);
const COOKIE_TTL = 600;
type Obj = Record<string, unknown>;
type Session = { accessJwt: string; did: string };
type KV = { get(key: string): Promise<string | null>; put(key: string, value: string, options?: { expirationTtl?: number }): Promise<void>; delete(key: string): Promise<void> };
type WorkerEnv = {
  ATPROTO_IDENTIFIER: string; ATPROTO_PASSWORD: string; ATPROTO_SERVICE?: string;
  GITHUB_CLIENT_ID: string; GITHUB_CLIENT_SECRET: string; GITHUB_ALLOWED_LOGIN: string;
  COOKIE_ENCRYPTION_KEY: string; STATE: KV; OAUTH_KV: KV; OAUTH_PROVIDER: OAuthHelpers;
};

const tools = [
  { name: "get_community_activity", description: "Get new Bluesky likes, followers, replies, mentions, quotes, and reposts. Uses a saved checkpoint when since is omitted. Set advanceCheckpoint only after successfully processing the response.", inputSchema: { type: "object", properties: { since: { type: "string", format: "date-time" }, limit: { type: "integer", minimum: 1, maximum: 100, default: 100 }, advanceCheckpoint: { type: "boolean", default: false } }, additionalProperties: false }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true } },
  { name: "get_post_context", description: "Read a Bluesky post and its surrounding thread before deciding whether or how to reply.", inputSchema: { type: "object", properties: { uri: { type: "string", pattern: "^at://" }, depth: { type: "integer", minimum: 0, maximum: 20, default: 6 }, parentHeight: { type: "integer", minimum: 0, maximum: 100, default: 20 } }, required: ["uri"], additionalProperties: false }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true } },
  { name: "reply_to_post", description: "Publish a Bluesky reply. During rollout, only use for a comment or mention on this account's own post after inspecting the thread. confirm must be true.", inputSchema: { type: "object", properties: { text: { type: "string", minLength: 1, maxLength: 3000 }, root: { type: "string", pattern: "^at://" }, parent: { type: "string", pattern: "^at://" }, langs: { type: "array", items: { type: "string" } }, confirm: { const: true } }, required: ["text", "root", "parent", "confirm"], additionalProperties: false }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true } }
];

function json(data: unknown, status = 200, headers: HeadersInit = {}): Response { return Response.json(data, { status, headers }); }
function rpc(id: unknown, result: unknown): Response { return json({ jsonrpc: "2.0", id, result }); }
function result(value: unknown): Obj { return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], structuredContent: value }; }
function required(args: Obj, key: string): string { const value = args[key]; if (typeof value !== "string" || !value) throw new Error(`${key} must be a non-empty string`); return value; }
function randomToken(): string { const bytes = crypto.getRandomValues(new Uint8Array(32)); return btoa(String.fromCharCode(...bytes)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function escapeHtml(value: unknown): string { return String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!)); }
function cookies(request: Request): Record<string, string> { return Object.fromEntries((request.headers.get("cookie") ?? "").split(";").map(v => v.trim().split("=", 2)).filter(v => v.length === 2) as [string, string][]); }
async function signature(value: string, secret: string): Promise<string> { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const sig = new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value))); return btoa(String.fromCharCode(...sig)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
async function signed(value: string, secret: string): Promise<string> { return `${value}.${await signature(value, secret)}`; }
async function verified(value: string | undefined, secret: string): Promise<string | null> { if (!value) return null; const split = value.lastIndexOf("."); if (split < 1) return null; const raw = value.slice(0, split), expected = await signature(raw, secret), actual = value.slice(split + 1); if (expected.length !== actual.length) return null; let diff = 0; for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ actual.charCodeAt(i); return diff === 0 ? raw : null; }
function setCookie(name: string, value: string, maxAge = COOKIE_TTL): string { return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`; }

async function xrpc<T>(env: WorkerEnv, path: string, options: { method?: "GET" | "POST"; session?: Session; query?: URLSearchParams; body?: unknown } = {}): Promise<T> {
  const url = new URL(`/xrpc/${path}`, env.ATPROTO_SERVICE || "https://bsky.social"); if (options.query) url.search = options.query.toString();
  const response = await fetch(url, { method: options.method ?? "GET", headers: { ...(options.session ? { Authorization: `Bearer ${options.session.accessJwt}` } : {}), ...(options.body === undefined ? {} : { "Content-Type": "application/json" }) }, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
  if (!response.ok) throw new Error(`Bluesky API ${path} failed (${response.status}): ${await response.text()}`); return (await response.json()) as T;
}
async function session(env: WorkerEnv): Promise<Session> { return xrpc(env, "com.atproto.server.createSession", { method: "POST", body: { identifier: env.ATPROTO_IDENTIFIER, password: env.ATPROTO_PASSWORD } }); }
function postParts(uri: string): { repo: string; collection: string; rkey: string } { const match = /^at:\/\/([^/]+)\/(app\.bsky\.feed\.post)\/([^/]+)$/.exec(uri); if (!match?.[1] || !match[2] || !match[3]) throw new Error("Expected an app.bsky.feed.post AT-URI"); return { repo: match[1], collection: match[2], rkey: match[3] }; }
async function cid(env: WorkerEnv, auth: Session, uri: string): Promise<string> { const record = await xrpc<{ cid?: string }>(env, "com.atproto.repo.getRecord", { session: auth, query: new URLSearchParams(postParts(uri)) }); if (!record.cid) throw new Error(`Could not resolve CID for ${uri}`); return record.cid; }
async function activity(env: WorkerEnv, args: Obj): Promise<Obj> { const since = typeof args.since === "string" ? args.since : (await env.STATE.get(CHECKPOINT_KEY)) ?? undefined; const limit = typeof args.limit === "number" ? Math.max(1, Math.min(100, Math.trunc(args.limit))) : 100; const auth = await session(env); const query = new URLSearchParams({ limit: String(limit) }); if (since) query.set("seenAt", since); const response = await xrpc<{ notifications: Obj[]; cursor?: string }>(env, "app.bsky.notification.listNotifications", { session: auth, query }); const checkedAt = new Date().toISOString(); const items = response.notifications.filter(item => typeof item.reason === "string" && REASONS.has(item.reason)).filter(item => !since || (typeof item.indexedAt === "string" && Date.parse(item.indexedAt) > Date.parse(since))).map(item => ({ id: `${String(item.uri)}:${String(item.cid)}:${String(item.reason)}`, kind: item.reason, uri: item.uri, cid: item.cid, indexedAt: item.indexedAt, isRead: item.isRead, author: item.author, record: item.record })); if (args.advanceCheckpoint === true) await env.STATE.put(CHECKPOINT_KEY, checkedAt); return { success: true, checkedAt, since: since ?? null, checkpointAdvanced: args.advanceCheckpoint === true, total: items.length, counts: Object.fromEntries([...REASONS].map(reason => [reason, items.filter(item => item.kind === reason).length])), activity: items, cursor: response.cursor ?? null }; }
async function context(env: WorkerEnv, args: Obj): Promise<Obj> { const auth = await session(env); const query = new URLSearchParams({ uri: required(args, "uri"), depth: String(typeof args.depth === "number" ? Math.trunc(args.depth) : 6), parentHeight: String(typeof args.parentHeight === "number" ? Math.trunc(args.parentHeight) : 20) }); const response = await xrpc<Obj>(env, "app.bsky.feed.getPostThread", { session: auth, query }); return { success: true, thread: response.thread }; }
async function reply(env: WorkerEnv, args: Obj): Promise<Obj> { if (args.confirm !== true) throw new Error("confirm must be true before publishing"); const text = required(args, "text"), root = required(args, "root"), parent = required(args, "parent"), auth = await session(env); const [rootCid, parentCid] = await Promise.all([cid(env, auth, root), cid(env, auth, parent)]); const record: Obj = { $type: "app.bsky.feed.post", text, createdAt: new Date().toISOString(), reply: { root: { uri: root, cid: rootCid }, parent: { uri: parent, cid: parentCid } } }; if (Array.isArray(args.langs)) record.langs = args.langs.filter(value => typeof value === "string"); const response = await xrpc<{ uri: string; cid: string }>(env, "com.atproto.repo.createRecord", { method: "POST", session: auth, body: { repo: auth.did, collection: "app.bsky.feed.post", record } }); return { success: true, uri: response.uri, cid: response.cid, replyTo: { root, parent } }; }
async function invoke(env: WorkerEnv, name: unknown, args: Obj): Promise<Obj> { if (name === "get_community_activity") return result(await activity(env, args)); if (name === "get_post_context") return result(await context(env, args)); if (name === "reply_to_post") return result(await reply(env, args)); throw new Error(`Unknown tool: ${String(name)}`); }
async function mcp(request: Request, env: WorkerEnv): Promise<Response> { if (request.method !== "POST") return new Response("Method not allowed", { status: 405 }); const message = (await request.json()) as Obj, id = message.id ?? null; if (message.method === "initialize") return rpc(id, { protocolVersion: "2025-06-18", capabilities: { tools: { listChanged: false } }, serverInfo: { name: "Bluesky Community Manager", version: "0.2.0" } }); if (message.method === "notifications/initialized") return new Response(null, { status: 202 }); if (message.method === "ping") return rpc(id, {}); if (message.method === "tools/list") return rpc(id, { tools }); if (message.method === "tools/call") { const params = (message.params ?? {}) as Obj; try { return rpc(id, await invoke(env, params.name, (params.arguments ?? {}) as Obj)); } catch (error) { return rpc(id, { isError: true, content: [{ type: "text", text: error instanceof Error ? error.message : String(error) }] }); } } return json({ jsonrpc: "2.0", id, error: { code: -32601, message: `Method not found: ${String(message.method)}` } }); }

function consentPage(clientName: string, csrf: string): Response { const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Authorize Bluesky Community Manager</title><style>body{font:16px system-ui;background:#f5f7fb;color:#172033;margin:0}.card{max-width:520px;margin:10vh auto;background:white;padding:32px;border-radius:16px;box-shadow:0 12px 40px #18243a1f}h1{font-size:25px}button{border:0;border-radius:9px;padding:12px 18px;font-weight:700;cursor:pointer}.yes{background:#087bea;color:white}.no{background:#e9edf5;color:#263148;margin-left:8px}.note{color:#526077;line-height:1.5}</style></head><body><main class="card"><h1>Authorize Bluesky Community Manager</h1><p><strong>${escapeHtml(clientName)}</strong> is requesting access to this MCP server.</p><p class="note">After you continue, GitHub will verify your identity. Only the approved GitHub account can finish authorization.</p><form method="post" action="/authorize"><input type="hidden" name="csrf" value="${escapeHtml(csrf)}"><button class="yes" name="decision" value="approve">Continue with GitHub</button><button class="no" name="decision" value="deny">Cancel</button></form></main></body></html>`; return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store", "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'" } }); }
async function authorize(request: Request, env: WorkerEnv): Promise<Response> {
  if (request.method === "GET") { const oauthRequest = await env.OAUTH_PROVIDER.parseAuthRequest(request); const client = await env.OAUTH_PROVIDER.lookupClient(oauthRequest.clientId); if (!client) return new Response("Unknown OAuth client", { status: 400 }); const id = randomToken(), csrf = randomToken(); await env.OAUTH_KV.put(`app:consent:${id}`, JSON.stringify({ oauthRequest, csrf }), { expirationTtl: COOKIE_TTL }); const response = consentPage(String((client as unknown as Obj).clientName ?? oauthRequest.clientId), csrf); response.headers.append("Set-Cookie", setCookie("oauth_consent", await signed(id, env.COOKIE_ENCRYPTION_KEY))); return response; }
  if (request.method !== "POST") return new Response("Method not allowed", { status: 405 }); const form = await request.formData(); const id = await verified(cookies(request).oauth_consent, env.COOKIE_ENCRYPTION_KEY); if (!id) return new Response("Authorization session is invalid or expired", { status: 400 }); const raw = await env.OAUTH_KV.get(`app:consent:${id}`); await env.OAUTH_KV.delete(`app:consent:${id}`); if (!raw) return new Response("Authorization session expired", { status: 400 }); const pending = JSON.parse(raw) as { oauthRequest: AuthRequest; csrf: string }; if (form.get("csrf") !== pending.csrf) return new Response("CSRF validation failed", { status: 403 }); if (form.get("decision") !== "approve") { const denied = new URL(pending.oauthRequest.redirectUri); denied.searchParams.set("error", "access_denied"); denied.searchParams.set("state", pending.oauthRequest.state); return Response.redirect(denied.toString(), 302); } const state = randomToken(); await env.OAUTH_KV.put(`app:github:${state}`, JSON.stringify(pending.oauthRequest), { expirationTtl: COOKIE_TTL }); const redirect = new URL("https://github.com/login/oauth/authorize"); redirect.searchParams.set("client_id", env.GITHUB_CLIENT_ID); redirect.searchParams.set("redirect_uri", `${new URL(request.url).origin}/callback`); redirect.searchParams.set("scope", "read:user"); redirect.searchParams.set("state", state); const response = Response.redirect(redirect.toString(), 302); response.headers.append("Set-Cookie", setCookie("github_state", await signed(state, env.COOKIE_ENCRYPTION_KEY))); return response;
}
async function callback(request: Request, env: WorkerEnv): Promise<Response> { const url = new URL(request.url), code = url.searchParams.get("code"), state = url.searchParams.get("state"), cookieState = await verified(cookies(request).github_state, env.COOKIE_ENCRYPTION_KEY); if (!code || !state || state !== cookieState) return new Response("GitHub OAuth state validation failed", { status: 400 }); const raw = await env.OAUTH_KV.get(`app:github:${state}`); await env.OAUTH_KV.delete(`app:github:${state}`); if (!raw) return new Response("GitHub authorization session expired", { status: 400 }); const tokenResponse = await fetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json", "User-Agent": "bluesky-community-manager" }, body: JSON.stringify({ client_id: env.GITHUB_CLIENT_ID, client_secret: env.GITHUB_CLIENT_SECRET, code, redirect_uri: `${url.origin}/callback` }) }); const tokenData = await tokenResponse.json() as { access_token?: string; error_description?: string }; if (!tokenResponse.ok || !tokenData.access_token) return new Response(`GitHub token exchange failed: ${tokenData.error_description ?? tokenResponse.status}`, { status: 502 }); const userResponse = await fetch("https://api.github.com/user", { headers: { Authorization: `Bearer ${tokenData.access_token}`, Accept: "application/vnd.github+json", "User-Agent": "bluesky-community-manager", "X-GitHub-Api-Version": "2022-11-28" } }); const user = await userResponse.json() as { id?: number; login?: string; name?: string }; if (!userResponse.ok || !user.id || !user.login) return new Response("Could not verify GitHub identity", { status: 502 }); if (user.login.toLowerCase() !== env.GITHUB_ALLOWED_LOGIN.toLowerCase()) return new Response("This GitHub account is not authorized for this Bluesky manager", { status: 403 }); const oauthRequest = JSON.parse(raw) as AuthRequest; const completed = await env.OAUTH_PROVIDER.completeAuthorization({ request: oauthRequest, userId: `github:${user.id}`, metadata: { label: user.login }, scope: oauthRequest.scope, props: { githubId: user.id, githubLogin: user.login } }); const response = Response.redirect(completed.redirectTo, 302); response.headers.append("Set-Cookie", setCookie("github_state", "", 0)); return response; }

const apiHandler = { async fetch(request: Request, env: WorkerEnv): Promise<Response> { return mcp(request, env); } };
const defaultHandler = { async fetch(request: Request, env: WorkerEnv): Promise<Response> { const path = new URL(request.url).pathname; if (path === "/health") return json({ ok: true, service: "bluesky-community-manager", authentication: "oauth" }); if (path === "/authorize") return authorize(request, env); if (path === "/callback") return callback(request, env); if (path === "/") return new Response("Bluesky Community Manager MCP server", { headers: { "Content-Type": "text/plain; charset=utf-8" } }); return new Response("Not found", { status: 404 }); } };

export default new OAuthProvider<WorkerEnv>({ apiRoute: "/mcp", apiHandler, defaultHandler, authorizeEndpoint: "/authorize", tokenEndpoint: "/token", clientRegistrationEndpoint: "/register", scopesSupported: ["bluesky.manage"], allowPlainPKCE: false, accessTokenTTL: 3600, refreshTokenTTL: 2592000, resourceMetadata: { resource: "https://bluesky-community-manager.eric-r-fraze.workers.dev/mcp", authorization_servers: ["https://bluesky-community-manager.eric-r-fraze.workers.dev"], scopes_supported: ["bluesky.manage"], bearer_methods_supported: ["header"], resource_name: "Bluesky Community Manager" } });

